[2025-04-01T19:25:47.212+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_a.load_data manual__2025-04-01T19:25:43.769357+00:00 [queued]>
[2025-04-01T19:25:47.215+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_a.load_data manual__2025-04-01T19:25:43.769357+00:00 [queued]>
[2025-04-01T19:25:47.215+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-01T19:25:47.220+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-01 19:25:43.769357+00:00
[2025-04-01T19:25:47.224+0000] {standard_task_runner.py:60} INFO - Started process 460 to run task
[2025-04-01T19:25:47.227+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_a', 'load_data', 'manual__2025-04-01T19:25:43.769357+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_dag.py', '--cfg-path', '/tmp/tmp7abvx2mf']
[2025-04-01T19:25:47.227+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask load_data
[2025-04-01T19:25:47.251+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_a.load_data manual__2025-04-01T19:25:43.769357+00:00 [running]> on host b0ef469a0134
[2025-04-01T19:25:47.284+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_a' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T19:25:43.769357+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T19:25:43.769357+00:00'
[2025-04-01T19:25:47.288+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-01T19:25:47.369+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-01T19:25:47.373+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_a, task_id=load_data, execution_date=20250401T192543, start_date=20250401T192547, end_date=20250401T192547
[2025-04-01T19:25:47.409+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-01T19:25:47.418+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
